/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/no-fly-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * No Fly Zones
         * @description The imported DGCA airspace overlay (red/amber rings + snapshot age).
         *
         *     Reads a local snapshot produced by ``scripts/import_no_fly_zones.py``.
         *     ``scope`` selects which snapshot to serve (``settings.no_fly_zones_files``,
         *     e.g. ``punjab`` or ``india``); an empty zone list when the scope is
         *     unknown or its file is missing.  The default ``punjab`` scope falls
         *     back to ``settings.no_fly_zones_file`` so existing deployments keep
         *     working unchanged.  Serves the frontend map overlay; the planner
         *     itself consumes the same rings via config (display scope never
         *     changes the planner's obstacle set).
         */
        get: operations["no_fly_zones_no_fly_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate-route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Route */
        post: operations["generate_route_generate_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replan
         * @description Recompute the route from the current position (same semantics as
         *     generate-route; kept as a separate endpoint so controllers can call
         *     it mid-mission without re-sending mission metadata).
         */
        post: operations["replan_replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Mission */
        post: operations["create_mission_mission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /health payload.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Buildings Parquet */
            buildings_parquet: string;
            /** Water Parquet */
            water_parquet: string | null;
            /** Memory Limit */
            memory_limit: string;
            /** Grid Resolution M */
            grid_resolution_m: number;
            /** Safety Margin M */
            safety_margin_m: number;
            /** Default Altitude M */
            default_altitude_m: number;
            /** Planner Algorithm */
            planner_algorithm: string;
        };
        /**
         * MissionCreateRequest
         * @description Body of POST /mission: register a mission and plan it.
         */
        MissionCreateRequest: {
            /** Start Lat */
            start_lat: number;
            /** Start Lon */
            start_lon: number;
            /** Goal Lat */
            goal_lat: number;
            /** Goal Lon */
            goal_lon: number;
            /** Altitude M */
            altitude_m?: number | null;
            /** Grid Resolution M */
            grid_resolution_m?: number | null;
            /** Safety Margin M */
            safety_margin_m?: number | null;
            /** Speed Mps */
            speed_mps?: number | null;
            /**
             * Snap Start Goal
             * @default false
             */
            snap_start_goal: boolean;
            /** Algorithm */
            algorithm?: ("astar" | "theta_star" | "visibility") | null;
            /** No Fly Zones */
            no_fly_zones?: components["schemas"]["NoFlyZone"][] | null;
            /** Mission Id */
            mission_id?: string | null;
        };
        /**
         * MissionRequest
         * @description Body of POST /generate-route.
         */
        MissionRequest: {
            /** Start Lat */
            start_lat: number;
            /** Start Lon */
            start_lon: number;
            /** Goal Lat */
            goal_lat: number;
            /** Goal Lon */
            goal_lon: number;
            /** Altitude M */
            altitude_m?: number | null;
            /** Grid Resolution M */
            grid_resolution_m?: number | null;
            /** Safety Margin M */
            safety_margin_m?: number | null;
            /** Speed Mps */
            speed_mps?: number | null;
            /**
             * Snap Start Goal
             * @default false
             */
            snap_start_goal: boolean;
            /** Algorithm */
            algorithm?: ("astar" | "theta_star" | "visibility") | null;
            /** No Fly Zones */
            no_fly_zones?: components["schemas"]["NoFlyZone"][] | null;
        };
        /**
         * MissionResponse
         * @description A registered mission with its plan.
         */
        MissionResponse: {
            /** Mission Id */
            mission_id: string;
            /** Status */
            status: string;
            route: components["schemas"]["RouteResponse"];
        };
        /**
         * NoFlyZone
         * @description A closed polygon ring of (lat, lon) vertices in WGS84.
         */
        NoFlyZone: {
            /** Ring */
            ring: [
                number,
                number
            ][];
        };
        /**
         * NoFlyZoneInfo
         * @description One no-fly polygon for the frontend overlay.
         */
        NoFlyZoneInfo: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "red" | "amber";
            /** Name */
            name: string;
            /** Ring */
            ring: [
                number,
                number
            ][];
        };
        /**
         * NoFlyZoneScopeInfo
         * @description One available overlay scope (e.g. punjab / india) and its size.
         */
        NoFlyZoneScopeInfo: {
            /** Name */
            name: string;
            /** Zones */
            zones: number;
            /** Fetched At */
            fetched_at: string | null;
        };
        /**
         * NoFlyZonesResponse
         * @description GET /no-fly-zones payload (red/amber overlay + snapshot age).
         *
         *     ``scope`` is the requested (or default) snapshot; ``available`` lists
         *     every configured scope so the frontend can render a switcher.
         */
        NoFlyZonesResponse: {
            /** Scope */
            scope: string;
            /** Fetched At */
            fetched_at: string | null;
            /** Source */
            source: string | null;
            /** Zones */
            zones: components["schemas"]["NoFlyZoneInfo"][];
            /** Available */
            available?: components["schemas"]["NoFlyZoneScopeInfo"][];
        };
        /**
         * ReplanRequest
         * @description Body of POST /replan: recompute from a new current position.
         */
        ReplanRequest: {
            /** Start Lat */
            start_lat: number;
            /** Start Lon */
            start_lon: number;
            /** Goal Lat */
            goal_lat: number;
            /** Goal Lon */
            goal_lon: number;
            /** Altitude M */
            altitude_m?: number | null;
            /** Grid Resolution M */
            grid_resolution_m?: number | null;
            /** Safety Margin M */
            safety_margin_m?: number | null;
            /** Speed Mps */
            speed_mps?: number | null;
            /**
             * Snap Start Goal
             * @default false
             */
            snap_start_goal: boolean;
            /** Algorithm */
            algorithm?: ("astar" | "theta_star" | "visibility") | null;
            /** No Fly Zones */
            no_fly_zones?: components["schemas"]["NoFlyZone"][] | null;
        };
        /**
         * RouteResponse
         * @description A computed route: GPS waypoints plus mission-level metadata.
         *
         *     Normally ``warning`` is null and ``backup_waypoints`` is the direct
         *     start->goal line (an operator-verifiable shortcut).  When no
         *     collision-free corridor exists, the planner degrades instead of failing:
         *     ``waypoints`` becomes a best-effort route (closest reachable point, then
         *     a straight segment to the goal) and ``warning`` explains why and what to
         *     verify before flight.
         */
        RouteResponse: {
            /** Mission Id */
            mission_id: string;
            /**
             * Distance
             * @description route length in metres
             */
            distance: number;
            /**
             * Estimated Time
             * @description flight time in seconds
             */
            estimated_time: number;
            /** Waypoints */
            waypoints: components["schemas"]["Waypoint"][];
            /** Warning */
            warning?: string | null;
            /** Backup Waypoints */
            backup_waypoints?: components["schemas"]["Waypoint"][] | null;
            /** Zones Crossed */
            zones_crossed?: components["schemas"]["NoFlyZoneInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Waypoint
         * @description A single GPS waypoint the drone controller must fly to.
         */
        Waypoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt */
            alt: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    no_fly_zones_no_fly_zones_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoFlyZonesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    generate_route_generate_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mission_mission_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
