/**
 * Typed API client (openapi-fetch) generated from the backend OpenAPI schema.
 *
 * Every backend call in the app goes through this client - there are no raw
 * `fetch` calls scattered through components.  The `paths` type comes from
 * src/types/api.generated.ts (generated by `npm run generate:api`), so
 * request bodies and responses are checked against the live backend models.
 */
import createClient from "openapi-fetch";

import type { paths } from "../types/api.generated";

export const API_BASE =
  (import.meta.env.VITE_API_BASE_URL as string | undefined) ?? "/api";

export const client = createClient<paths>({ baseUrl: API_BASE });

/** Normalised API error - `detail` from the backend when available. */
export class ApiError extends Error {
  readonly status: number | undefined;

  constructor(message: string, status?: number) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

/** Extract a human-readable message from an openapi-fetch error result. */
export function errorMessage(
  err: unknown,
  fallback: string,
): ApiError {
  if (err instanceof ApiError) return err;
  if (err instanceof TypeError) {
    // fetch-level failure: backend unreachable
    return new ApiError(
      `Cannot reach the planner API at "${API_BASE}". Is the backend running? (${err.message})`,
    );
  }
  const raw = err as {
    error?: { detail?: unknown };
    response?: { status?: number };
  };
  const detail = raw.error?.detail;
  const message =
    typeof detail === "string"
      ? detail
      : Array.isArray(detail)
        ? "Request validation failed"
        : fallback;
  return new ApiError(message, raw.response?.status);
}
