-- Mangalore smart recycle routing schema.
--
-- Preconditions:
--   - Run against the PostgreSQL database that already contains the
--     mangalore.roads, mangalore.roads_noded, and
--     mangalore.roads_noded_vertices_pgr network tables.
--   - PostGIS and pgRouting extensions must already be installed.
--   - Routing geometries remain in EPSG:3857. App-facing latitude/longitude
--     are transformed into mangalore.locations.geom by trigger.

BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'postgis') THEN
        RAISE EXCEPTION 'PostGIS extension is required before running this schema';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgrouting') THEN
        RAISE EXCEPTION 'pgRouting extension is required before running this schema';
    END IF;
END;
$$;

CREATE SCHEMA IF NOT EXISTS mangalore;

DO $$
BEGIN
    IF to_regclass('mangalore.locations') IS NULL THEN
        CREATE TABLE mangalore.locations (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(150) NOT NULL,
            location_type text NOT NULL,
            address varchar(255),
            latitude numeric(10,7) NOT NULL,
            longitude numeric(10,7) NOT NULL,
            place_query text,
            geocoding_source text,
            geocoded_at timestamptz,
            geom geometry(Point,3857),
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_location_name UNIQUE (name),
            CONSTRAINT locations_location_type_check
                CHECK (location_type = ANY (ARRAY[
                    'DEPOT'::text,
                    'BIN'::text,
                    'CUSTOMER'::text,
                    'VENDOR'::text,
                    'TRUCK_STOP'::text
                ]))
        );
    END IF;
END;
$$;

ALTER TABLE mangalore.locations
    ALTER COLUMN location_type TYPE text,
    ADD COLUMN IF NOT EXISTS address varchar(255),
    ADD COLUMN IF NOT EXISTS latitude numeric(10,7),
    ADD COLUMN IF NOT EXISTS longitude numeric(10,7),
    ADD COLUMN IF NOT EXISTS place_query text,
    ADD COLUMN IF NOT EXISTS geocoding_source text,
    ADD COLUMN IF NOT EXISTS geocoded_at timestamptz,
    ADD COLUMN IF NOT EXISTS geom geometry(Point,3857),
    ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'mangalore.locations'::regclass
          AND attname = 'id'
          AND attidentity <> ''
    ) THEN
        ALTER TABLE mangalore.locations
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'mangalore.locations'::regclass
          AND conname = 'uq_location_name'
    ) THEN
        ALTER TABLE mangalore.locations
            ADD CONSTRAINT uq_location_name UNIQUE (name);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'mangalore.locations'::regclass
          AND conname = 'locations_location_type_check'
    ) THEN
        ALTER TABLE mangalore.locations
            DROP CONSTRAINT locations_location_type_check;
    END IF;

    ALTER TABLE mangalore.locations
        ADD CONSTRAINT locations_location_type_check
        CHECK (location_type = ANY (ARRAY[
            'DEPOT'::text,
            'BIN'::text,
            'CUSTOMER'::text,
            'VENDOR'::text,
            'TRUCK_STOP'::text
        ]));
END;
$$;

ALTER TABLE mangalore.locations
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN location_type SET NOT NULL,
    ALTER COLUMN latitude SET NOT NULL,
    ALTER COLUMN longitude SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_locations_type
    ON mangalore.locations (location_type);

CREATE INDEX IF NOT EXISTS idx_locations_geom
    ON mangalore.locations USING gist (geom);

CREATE TABLE IF NOT EXISTS mangalore.location_network_nodes (
    location_id bigint PRIMARY KEY,
    vertex_id bigint NOT NULL,
    road_segment_id bigint,
    original_geom geometry(Point,3857),
    snapped_geom geometry(Point,3857),
    distance_to_road double precision,
    distance_to_vertex double precision,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_location_network_location
        FOREIGN KEY (location_id) REFERENCES mangalore.locations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_location_network_vertex
        FOREIGN KEY (vertex_id) REFERENCES mangalore.roads_noded_vertices_pgr(id),
    CONSTRAINT fk_location_network_road_segment
        FOREIGN KEY (road_segment_id) REFERENCES mangalore.roads_noded(id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'mangalore'
          AND table_name = 'location_network_nodes'
          AND column_name = 'distance_m'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'mangalore'
          AND table_name = 'location_network_nodes'
          AND column_name = 'distance_to_road'
    ) THEN
        ALTER TABLE mangalore.location_network_nodes
            RENAME COLUMN distance_m TO distance_to_road;
    END IF;
END;
$$;

ALTER TABLE mangalore.location_network_nodes
    ADD COLUMN IF NOT EXISTS original_geom geometry(Point,3857),
    ADD COLUMN IF NOT EXISTS snapped_geom geometry(Point,3857),
    ADD COLUMN IF NOT EXISTS distance_to_road double precision,
    ADD COLUMN IF NOT EXISTS distance_to_vertex double precision,
    ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE mangalore.location_network_nodes
    ALTER COLUMN vertex_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_location_network_vertex
    ON mangalore.location_network_nodes (vertex_id);

CREATE INDEX IF NOT EXISTS idx_location_network_road_segment
    ON mangalore.location_network_nodes (road_segment_id);

CREATE INDEX IF NOT EXISTS idx_location_network_original_geom
    ON mangalore.location_network_nodes USING gist (original_geom);

CREATE INDEX IF NOT EXISTS idx_location_network_snapped_geom
    ON mangalore.location_network_nodes USING gist (snapped_geom);

CREATE TABLE IF NOT EXISTS mangalore.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL UNIQUE,
    contact_name varchar(150),
    phone varchar(40),
    email varchar(254),
    pickup_notes text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_customers_location
        FOREIGN KEY (location_id) REFERENCES mangalore.locations(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mangalore.vendors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL UNIQUE,
    contact_name varchar(150),
    phone varchar(40),
    email varchar(254),
    accepted_waste_types text[] NOT NULL DEFAULT ARRAY[]::text[],
    pickup_days text[] NOT NULL DEFAULT ARRAY[
        'Monday'::text,
        'Tuesday'::text,
        'Wednesday'::text,
        'Thursday'::text,
        'Friday'::text
    ],
    acceptance_details text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_vendors_location
        FOREIGN KEY (location_id) REFERENCES mangalore.locations(id)
        ON DELETE CASCADE
);

ALTER TABLE mangalore.vendors
    ADD COLUMN IF NOT EXISTS pickup_days text[] NOT NULL DEFAULT ARRAY[
        'Monday'::text,
        'Tuesday'::text,
        'Wednesday'::text,
        'Thursday'::text,
        'Friday'::text
    ];

CREATE TABLE IF NOT EXISTS mangalore.trucks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_code varchar(80) NOT NULL UNIQUE,
    registration_number varchar(80) UNIQUE,
    capacity_kg numeric(12,3),
    capacity_m3 numeric(12,3),
    home_depot_location_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_trucks_home_depot
        FOREIGN KEY (home_depot_location_id) REFERENCES mangalore.locations(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS mangalore.truck_availability (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id bigint NOT NULL,
    available_from timestamptz NOT NULL,
    available_until timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'AVAILABLE',
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_truck_availability_truck
        FOREIGN KEY (truck_id) REFERENCES mangalore.trucks(id)
        ON DELETE CASCADE,
    CONSTRAINT truck_availability_status_check
        CHECK (status = ANY (ARRAY[
            'AVAILABLE'::text,
            'RESERVED'::text,
            'MAINTENANCE'::text,
            'UNAVAILABLE'::text
        ])),
    CONSTRAINT truck_availability_time_check
        CHECK (available_until > available_from)
);

CREATE TABLE IF NOT EXISTS mangalore.service_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code varchar(80) NOT NULL UNIQUE,
    customer_id bigint,
    vendor_id bigint,
    pickup_location_id bigint NOT NULL,
    dropoff_location_id bigint,
    waste_type text,
    estimated_weight_kg numeric(12,3),
    status text NOT NULL DEFAULT 'PENDING',
    requested_at timestamptz NOT NULL DEFAULT now(),
    service_window_start timestamptz,
    service_window_end timestamptz,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_service_orders_customer
        FOREIGN KEY (customer_id) REFERENCES mangalore.customers(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_service_orders_vendor
        FOREIGN KEY (vendor_id) REFERENCES mangalore.vendors(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_service_orders_pickup_location
        FOREIGN KEY (pickup_location_id) REFERENCES mangalore.locations(id),
    CONSTRAINT fk_service_orders_dropoff_location
        FOREIGN KEY (dropoff_location_id) REFERENCES mangalore.locations(id),
    CONSTRAINT service_orders_status_check
        CHECK (status = ANY (ARRAY[
            'PENDING'::text,
            'PLANNED'::text,
            'IN_PROGRESS'::text,
            'COMPLETED'::text,
            'CANCELLED'::text
        ])),
    CONSTRAINT service_orders_window_check
        CHECK (
            service_window_start IS NULL
            OR service_window_end IS NULL
            OR service_window_end > service_window_start
        )
);

CREATE TABLE IF NOT EXISTS mangalore.route_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code varchar(80) NOT NULL UNIQUE,
    truck_id bigint,
    depot_location_id bigint,
    status text NOT NULL DEFAULT 'DRAFT',
    planned_start_at timestamptz,
    planned_end_at timestamptz,
    total_distance_m double precision,
    total_cost double precision,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_route_plans_truck
        FOREIGN KEY (truck_id) REFERENCES mangalore.trucks(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_route_plans_depot
        FOREIGN KEY (depot_location_id) REFERENCES mangalore.locations(id)
        ON DELETE SET NULL,
    CONSTRAINT route_plans_status_check
        CHECK (status = ANY (ARRAY[
            'DRAFT'::text,
            'PLANNED'::text,
            'DISPATCHED'::text,
            'COMPLETED'::text,
            'CANCELLED'::text
        ])),
    CONSTRAINT route_plans_time_check
        CHECK (
            planned_start_at IS NULL
            OR planned_end_at IS NULL
            OR planned_end_at > planned_start_at
        )
);

CREATE TABLE IF NOT EXISTS mangalore.route_plan_stops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_plan_id bigint NOT NULL,
    stop_sequence integer NOT NULL,
    location_id bigint NOT NULL,
    service_order_id bigint,
    stop_type text NOT NULL,
    planned_arrival_at timestamptz,
    planned_departure_at timestamptz,
    actual_arrival_at timestamptz,
    actual_departure_at timestamptz,
    notes text,
    CONSTRAINT fk_route_plan_stops_plan
        FOREIGN KEY (route_plan_id) REFERENCES mangalore.route_plans(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_route_plan_stops_location
        FOREIGN KEY (location_id) REFERENCES mangalore.locations(id),
    CONSTRAINT fk_route_plan_stops_service_order
        FOREIGN KEY (service_order_id) REFERENCES mangalore.service_orders(id)
        ON DELETE SET NULL,
    CONSTRAINT uq_route_plan_stop_sequence
        UNIQUE (route_plan_id, stop_sequence),
    CONSTRAINT route_plan_stops_type_check
        CHECK (stop_type = ANY (ARRAY[
            'DEPOT_START'::text,
            'PICKUP'::text,
            'DROPOFF'::text,
            'DEPOT_END'::text,
            'BREAK'::text
        ]))
);

CREATE TABLE IF NOT EXISTS mangalore.route_plan_segments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_plan_id bigint NOT NULL,
    from_stop_id bigint NOT NULL,
    to_stop_id bigint NOT NULL,
    segment_sequence integer NOT NULL,
    start_vertex_id bigint NOT NULL,
    end_vertex_id bigint NOT NULL,
    distance_m double precision,
    cost double precision,
    path jsonb,
    geom geometry(MultiLineString,3857),
    CONSTRAINT fk_route_plan_segments_plan
        FOREIGN KEY (route_plan_id) REFERENCES mangalore.route_plans(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_route_plan_segments_from_stop
        FOREIGN KEY (from_stop_id) REFERENCES mangalore.route_plan_stops(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_route_plan_segments_to_stop
        FOREIGN KEY (to_stop_id) REFERENCES mangalore.route_plan_stops(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_route_plan_segments_start_vertex
        FOREIGN KEY (start_vertex_id) REFERENCES mangalore.roads_noded_vertices_pgr(id),
    CONSTRAINT fk_route_plan_segments_end_vertex
        FOREIGN KEY (end_vertex_id) REFERENCES mangalore.roads_noded_vertices_pgr(id),
    CONSTRAINT uq_route_plan_segment_sequence
        UNIQUE (route_plan_id, segment_sequence),
    CONSTRAINT route_plan_segments_distinct_stops_check
        CHECK (from_stop_id <> to_stop_id)
);

CREATE INDEX IF NOT EXISTS idx_customers_location
    ON mangalore.customers (location_id);

CREATE INDEX IF NOT EXISTS idx_vendors_location
    ON mangalore.vendors (location_id);

CREATE INDEX IF NOT EXISTS idx_trucks_home_depot
    ON mangalore.trucks (home_depot_location_id);

CREATE INDEX IF NOT EXISTS idx_truck_availability_truck_time
    ON mangalore.truck_availability (truck_id, available_from, available_until);

CREATE INDEX IF NOT EXISTS idx_service_orders_status
    ON mangalore.service_orders (status);

CREATE INDEX IF NOT EXISTS idx_service_orders_pickup_location
    ON mangalore.service_orders (pickup_location_id);

CREATE INDEX IF NOT EXISTS idx_service_orders_dropoff_location
    ON mangalore.service_orders (dropoff_location_id);

CREATE INDEX IF NOT EXISTS idx_route_plans_truck
    ON mangalore.route_plans (truck_id);

CREATE INDEX IF NOT EXISTS idx_route_plan_stops_plan_sequence
    ON mangalore.route_plan_stops (route_plan_id, stop_sequence);

CREATE INDEX IF NOT EXISTS idx_route_plan_stops_location
    ON mangalore.route_plan_stops (location_id);

CREATE INDEX IF NOT EXISTS idx_route_plan_segments_plan_sequence
    ON mangalore.route_plan_segments (route_plan_id, segment_sequence);

CREATE INDEX IF NOT EXISTS idx_route_plan_segments_geom
    ON mangalore.route_plan_segments USING gist (geom);

CREATE TABLE IF NOT EXISTS mangalore.routing_edges (
    id bigint PRIMARY KEY,
    old_road_id integer,
    source bigint NOT NULL,
    target bigint NOT NULL,
    length_m double precision NOT NULL,
    cost double precision NOT NULL,
    reverse_cost double precision NOT NULL,
    osm_id bigint,
    name varchar,
    highway varchar,
    oneway varchar,
    surface varchar,
    width varchar,
    geom geometry(LineString,3857) NOT NULL
);

TRUNCATE TABLE mangalore.routing_edges;

INSERT INTO mangalore.routing_edges (
    id,
    old_road_id,
    source,
    target,
    length_m,
    cost,
    reverse_cost,
    osm_id,
    name,
    highway,
    oneway,
    surface,
    width,
    geom
)
SELECT
    rn.id,
    rn.old_id,
    rn.source,
    rn.target,
    ST_Length(rn.geom) AS length_m,
    CASE
        WHEN COALESCE(NULLIF(btrim(r.oneway), ''), 'no') = '-1' THEN -1.0
        ELSE ST_Length(rn.geom)
    END AS cost,
    CASE
        WHEN COALESCE(NULLIF(btrim(r.oneway), ''), 'no') IN ('yes', 'true', '1') THEN -1.0
        ELSE ST_Length(rn.geom)
    END AS reverse_cost,
    r.osm_id,
    r.name,
    r.highway,
    r.oneway,
    r.surface,
    r.width,
    rn.geom
FROM mangalore.roads_noded AS rn
LEFT JOIN mangalore.roads AS r
    ON r.fid = rn.old_id
WHERE rn.source IS NOT NULL
  AND rn.target IS NOT NULL
  AND rn.geom IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_routing_edges_source
    ON mangalore.routing_edges (source);

CREATE INDEX IF NOT EXISTS idx_routing_edges_target
    ON mangalore.routing_edges (target);

CREATE INDEX IF NOT EXISTS idx_routing_edges_old_road
    ON mangalore.routing_edges (old_road_id);

CREATE INDEX IF NOT EXISTS idx_routing_edges_geom
    ON mangalore.routing_edges USING gist (geom);

CREATE OR REPLACE FUNCTION mangalore.set_location_geom_3857()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.geom := ST_Transform(
        ST_SetSRID(
            ST_MakePoint(NEW.longitude::double precision, NEW.latitude::double precision),
            4326
        ),
        3857
    );

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION mangalore.snap_location_to_network()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    nearest_edge record;
    nearest_vertex record;
BEGIN
    IF NEW.geom IS NULL THEN
        RAISE EXCEPTION 'Location % has no EPSG:3857 geometry to snap', NEW.id;
    END IF;

    SELECT
        rn.id AS road_segment_id,
        ST_ClosestPoint(rn.geom, NEW.geom) AS snapped_geom,
        ST_Distance(NEW.geom, rn.geom) AS distance_to_road
    INTO nearest_edge
    FROM mangalore.roads_noded AS rn
    WHERE rn.geom IS NOT NULL
    ORDER BY rn.geom <-> NEW.geom
    LIMIT 1;

    IF nearest_edge.road_segment_id IS NULL THEN
        RAISE EXCEPTION 'Cannot snap location %, no mangalore.roads_noded edges found', NEW.id;
    END IF;

    SELECT
        v.id AS vertex_id,
        ST_Distance(nearest_edge.snapped_geom, v.the_geom) AS distance_to_vertex
    INTO nearest_vertex
    FROM mangalore.roads_noded_vertices_pgr AS v
    WHERE v.the_geom IS NOT NULL
    ORDER BY v.the_geom <-> nearest_edge.snapped_geom
    LIMIT 1;

    IF nearest_vertex.vertex_id IS NULL THEN
        RAISE EXCEPTION 'Cannot snap location %, no mangalore.roads_noded_vertices_pgr vertices found', NEW.id;
    END IF;

    INSERT INTO mangalore.location_network_nodes (
        location_id,
        vertex_id,
        road_segment_id,
        original_geom,
        snapped_geom,
        distance_to_road,
        distance_to_vertex,
        updated_at
    )
    VALUES (
        NEW.id,
        nearest_vertex.vertex_id,
        nearest_edge.road_segment_id,
        NEW.geom,
        nearest_edge.snapped_geom,
        nearest_edge.distance_to_road,
        nearest_vertex.distance_to_vertex,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (location_id) DO UPDATE
    SET vertex_id = EXCLUDED.vertex_id,
        road_segment_id = EXCLUDED.road_segment_id,
        original_geom = EXCLUDED.original_geom,
        snapped_geom = EXCLUDED.snapped_geom,
        distance_to_road = EXCLUDED.distance_to_road,
        distance_to_vertex = EXCLUDED.distance_to_vertex,
        updated_at = CURRENT_TIMESTAMP;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_locations_set_geom_3857 ON mangalore.locations;
CREATE TRIGGER trg_locations_set_geom_3857
BEFORE INSERT OR UPDATE OF latitude, longitude
ON mangalore.locations
FOR EACH ROW
EXECUTE FUNCTION mangalore.set_location_geom_3857();

DROP TRIGGER IF EXISTS trg_locations_snap_to_network ON mangalore.locations;
CREATE TRIGGER trg_locations_snap_to_network
AFTER INSERT OR UPDATE OF latitude, longitude, geom
ON mangalore.locations
FOR EACH ROW
EXECUTE FUNCTION mangalore.snap_location_to_network();

UPDATE mangalore.locations
SET latitude = latitude
WHERE latitude IS NOT NULL
  AND longitude IS NOT NULL;

WITH sample_locations (name, location_type, address, latitude, longitude, place_query) AS (
    VALUES
        ('MCC Central Depot', 'DEPOT', 'State Bank, Mangaluru', 12.8692500, 74.8425800, 'State Bank Mangaluru'),
        ('Kadri Transfer Depot', 'DEPOT', 'Kadri, Mangaluru', 12.8950400, 74.8557400, 'Kadri Mangaluru'),
        ('Panambur Logistics Yard', 'TRUCK_STOP', 'Panambur, Mangaluru', 12.9459200, 74.8046200, 'Panambur Mangaluru'),
        ('EcoSort Baikampady Vendor', 'VENDOR', 'Baikampady Industrial Area', 12.9599800, 74.8197600, 'Baikampady Industrial Area'),
        ('GreenLoop Jeppu Vendor', 'VENDOR', 'Jeppu Market Road', 12.8546400, 74.8520400, 'Jeppu Mangaluru'),
        ('Coastal Plastics Bunder Vendor', 'VENDOR', 'Old Port Road, Bunder', 12.8667600, 74.8389000, 'Bunder Mangaluru'),
        ('Surathkal Metals Vendor', 'VENDOR', 'Surathkal Main Road', 13.0066200, 74.7941800, 'Surathkal Mangaluru'),
        ('Kadri Park Apartments', 'CUSTOMER', 'Kadri Park Road', 12.8958600, 74.8535900, 'Kadri Park Mangaluru'),
        ('Bejai Commercial Complex', 'CUSTOMER', 'Bejai Main Road', 12.8977600, 74.8418900, 'Bejai Mangaluru'),
        ('Kankanady Market Cluster', 'CUSTOMER', 'Kankanady Market', 12.8720600, 74.8589200, 'Kankanady Mangaluru'),
        ('Attavar Medical Campus', 'CUSTOMER', 'Attavar', 12.8631800, 74.8495700, 'Attavar Mangaluru'),
        ('Hampankatta Retail Row', 'CUSTOMER', 'Hampankatta', 12.8708800, 74.8439000, 'Hampankatta Mangaluru'),
        ('Falnir Office Block', 'CUSTOMER', 'Falnir Road', 12.8664300, 74.8493400, 'Falnir Mangaluru'),
        ('Urwa Stores Community', 'CUSTOMER', 'Urwa Stores', 12.9026300, 74.8304100, 'Urwa Stores Mangaluru'),
        ('Derebail Residential Ward', 'CUSTOMER', 'Derebail', 12.9238300, 74.8444600, 'Derebail Mangaluru'),
        ('Kuloor Warehouse Row', 'CUSTOMER', 'Kuloor Ferry Road', 12.9271800, 74.8287500, 'Kuloor Mangaluru'),
        ('Bondel School Zone', 'CUSTOMER', 'Bondel', 12.9256900, 74.8612200, 'Bondel Mangaluru'),
        ('Thokkottu Retail Street', 'CUSTOMER', 'Thokkottu', 12.8163900, 74.8600700, 'Thokkottu Mangaluru'),
        ('Pumpwell Junction Mall', 'CUSTOMER', 'Pumpwell', 12.8619800, 74.8644700, 'Pumpwell Mangaluru'),
        ('Surathkal College Campus', 'CUSTOMER', 'Surathkal', 13.0101700, 74.7949700, 'Surathkal Mangaluru'),
        ('Ullal Community Market', 'CUSTOMER', 'Ullal', 12.8057500, 74.8608400, 'Ullal Mangaluru'),
        ('Ladyhill Housing Block', 'CUSTOMER', 'Ladyhill', 12.8917400, 74.8321500, 'Ladyhill Mangaluru'),
        ('Mannagudda Temple Street', 'CUSTOMER', 'Mannagudda', 12.8846200, 74.8372500, 'Mannagudda Mangaluru'),
        ('Car Street Market Lane', 'CUSTOMER', 'Car Street', 12.8746700, 74.8383300, 'Car Street Mangaluru'),
        ('Bolar Fisheries Row', 'CUSTOMER', 'Bolar', 12.8526800, 74.8383200, 'Bolar Mangaluru'),
        ('Pandeshwar Office Towers', 'CUSTOMER', 'Pandeshwar', 12.8605700, 74.8410300, 'Pandeshwar Mangaluru'),
        ('Nanthoor Junction Shops', 'CUSTOMER', 'Nanthoor', 12.8878800, 74.8701200, 'Nanthoor Mangaluru'),
        ('Shaktinagar Community Hall', 'CUSTOMER', 'Shaktinagar', 12.8952800, 74.8791300, 'Shaktinagar Mangaluru'),
        ('Maryhill Ward Office', 'CUSTOMER', 'Maryhill', 12.9135100, 74.8560900, 'Maryhill Mangaluru'),
        ('Kavoor Commercial Strip', 'CUSTOMER', 'Kavoor', 12.9345500, 74.8534600, 'Kavoor Mangaluru'),
        ('Kottara Chowki Stores', 'CUSTOMER', 'Kottara Chowki', 12.9184100, 74.8318600, 'Kottara Chowki Mangaluru'),
        ('Baikampady Factory Gate', 'CUSTOMER', 'Baikampady', 12.9593600, 74.8238800, 'Baikampady Mangaluru'),
        ('Panambur Port Canteen', 'CUSTOMER', 'Panambur', 12.9488700, 74.8077400, 'Panambur Mangaluru')
),
upserted_locations AS (
    INSERT INTO mangalore.locations (
        name,
        location_type,
        address,
        latitude,
        longitude,
        place_query,
        geocoding_source,
        geocoded_at
    )
    SELECT name, location_type, address, latitude, longitude, place_query, 'sample-seed', now()
    FROM sample_locations
    ON CONFLICT (name) DO UPDATE
    SET
        location_type = EXCLUDED.location_type,
        address = EXCLUDED.address,
        latitude = EXCLUDED.latitude,
        longitude = EXCLUDED.longitude,
        place_query = EXCLUDED.place_query,
        geocoding_source = 'sample-seed',
        geocoded_at = now()
    RETURNING id, name
),
all_sample_locations AS (
    SELECT id, name
    FROM upserted_locations
    UNION
    SELECT id, name
    FROM mangalore.locations
    WHERE name IN (SELECT name FROM sample_locations)
),
sample_customers (location_name, contact_name, phone, email, pickup_notes) AS (
    VALUES
        ('Kadri Park Apartments', 'Rashmi Rao', '+91 824 555 0101', 'rashmi.rao@example.com', 'Security gate entry before 11:00'),
        ('Bejai Commercial Complex', 'Anil Dsouza', '+91 824 555 0102', 'anil.dsouza@example.com', 'Use service lane behind block B'),
        ('Kankanady Market Cluster', 'Meera Shenoy', '+91 824 555 0103', 'meera.shenoy@example.com', 'Wet waste bay is on the south side'),
        ('Attavar Medical Campus', 'Dr Priya Kamath', '+91 824 555 0104', 'priya.kamath@example.com', 'Report to facilities desk'),
        ('Hampankatta Retail Row', 'Irfan Sheikh', '+91 824 555 0105', 'irfan.sheikh@example.com', 'Morning pickup only'),
        ('Falnir Office Block', 'Naveen Kumar', '+91 824 555 0106', 'naveen.kumar@example.com', 'Basement loading dock'),
        ('Urwa Stores Community', 'Latha Pinto', '+91 824 555 0107', 'latha.pinto@example.com', 'Call 15 minutes before arrival'),
        ('Derebail Residential Ward', 'Suresh Bhandary', '+91 824 555 0108', 'suresh.bhandary@example.com', 'Gate 2 access'),
        ('Kuloor Warehouse Row', 'Farah Ali', '+91 824 555 0109', 'farah.ali@example.com', 'Large sacks near weigh bridge'),
        ('Bondel School Zone', 'Joseph Martis', '+91 824 555 0110', 'joseph.martis@example.com', 'Avoid school dismissal time'),
        ('Thokkottu Retail Street', 'Vijay Hegde', '+91 824 555 0111', 'vijay.hegde@example.com', 'Pickup from rear lane'),
        ('Pumpwell Junction Mall', 'Shalini Nair', '+91 824 555 0112', 'shalini.nair@example.com', 'Dock opens after 10:00'),
        ('Surathkal College Campus', 'Kiran Pai', '+91 824 555 0113', 'kiran.pai@example.com', 'Engineering block collection point'),
        ('Ullal Community Market', 'Ayesha Rahman', '+91 824 555 0114', 'ayesha.rahman@example.com', 'Segregated bags beside office'),
        ('Ladyhill Housing Block', 'Rohan Castelino', '+91 824 555 0115', 'rohan.castelino@example.com', 'North gate collection point'),
        ('Mannagudda Temple Street', 'Sahana Kini', '+91 824 555 0116', 'sahana.kini@example.com', 'Keep truck clear of temple entrance'),
        ('Car Street Market Lane', 'Deepak Prabhu', '+91 824 555 0117', 'deepak.prabhu@example.com', 'Dense lane, small vehicle preferred'),
        ('Bolar Fisheries Row', 'Rafiq Ahmed', '+91 824 555 0118', 'rafiq.ahmed@example.com', 'Collect from ice plant side'),
        ('Pandeshwar Office Towers', 'Maya Fernandes', '+91 824 555 0119', 'maya.fernandes@example.com', 'Office tower basement dock'),
        ('Nanthoor Junction Shops', 'Ganesh Rao', '+91 824 555 0120', 'ganesh.rao@example.com', 'Traffic heavy near junction'),
        ('Shaktinagar Community Hall', 'Elina Dsouza', '+91 824 555 0121', 'elina.dsouza@example.com', 'Community hall side gate'),
        ('Maryhill Ward Office', 'Pradeep K', '+91 824 555 0122', 'pradeep.k@example.com', 'Ward office collection bay'),
        ('Kavoor Commercial Strip', 'Anusha Rai', '+91 824 555 0123', 'anusha.rai@example.com', 'Shop row pickup'),
        ('Kottara Chowki Stores', 'Sameer Poojary', '+91 824 555 0124', 'sameer.poojary@example.com', 'Service road access'),
        ('Baikampady Factory Gate', 'Rakesh Naik', '+91 824 555 0125', 'rakesh.naik@example.com', 'Factory gate weighment needed'),
        ('Panambur Port Canteen', 'Nisha Amin', '+91 824 555 0126', 'nisha.amin@example.com', 'Port canteen rear entry')
)
INSERT INTO mangalore.customers (location_id, contact_name, phone, email, pickup_notes)
SELECT l.id, c.contact_name, c.phone, c.email, c.pickup_notes
FROM sample_customers AS c
JOIN all_sample_locations AS l ON l.name = c.location_name
ON CONFLICT (location_id) DO UPDATE
SET
    contact_name = EXCLUDED.contact_name,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    pickup_notes = EXCLUDED.pickup_notes,
    is_active = true,
    updated_at = now();

WITH sample_vendors (location_name, contact_name, phone, email, accepted_waste_types, pickup_days, acceptance_details) AS (
    VALUES
        ('EcoSort Baikampady Vendor', 'Harish Nayak', '+91 824 555 0201', 'intake@ecosort.example.com', ARRAY['plastic', 'paper', 'cardboard']::text[], ARRAY['Monday', 'Wednesday', 'Friday']::text[], 'Dry recyclables, baled or bagged'),
        ('GreenLoop Jeppu Vendor', 'Sandra Lobo', '+91 824 555 0202', 'ops@greenloop.example.com', ARRAY['organic', 'garden', 'food']::text[], ARRAY['Tuesday', 'Thursday', 'Saturday']::text[], 'Organic loads below 1.5 tonnes'),
        ('Coastal Plastics Bunder Vendor', 'Mohammed Basheer', '+91 824 555 0203', 'pickup@coastalplastics.example.com', ARRAY['plastic', 'e-waste']::text[], ARRAY['Monday', 'Thursday']::text[], 'Separated PET, HDPE, and small e-waste'),
        ('Surathkal Metals Vendor', 'Prakash Shetty', '+91 824 555 0204', 'yard@surathkalmetals.example.com', ARRAY['metal', 'scrap', 'appliance']::text[], ARRAY['Wednesday', 'Saturday']::text[], 'Metal scrap and appliances only')
)
INSERT INTO mangalore.vendors (
    location_id,
    contact_name,
    phone,
    email,
    accepted_waste_types,
    pickup_days,
    acceptance_details
)
SELECT l.id, v.contact_name, v.phone, v.email, v.accepted_waste_types, v.pickup_days, v.acceptance_details
FROM sample_vendors AS v
JOIN mangalore.locations AS l ON l.name = v.location_name
ON CONFLICT (location_id) DO UPDATE
SET
    contact_name = EXCLUDED.contact_name,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    accepted_waste_types = EXCLUDED.accepted_waste_types,
    pickup_days = EXCLUDED.pickup_days,
    acceptance_details = EXCLUDED.acceptance_details,
    is_active = true,
    updated_at = now();

WITH sample_trucks (truck_code, registration_number, capacity_kg, capacity_m3, depot_name) AS (
    VALUES
        ('MRF-TRUCK-01', 'KA19AB1001', 2200.000, 16.000, 'MCC Central Depot'),
        ('MRF-TRUCK-02', 'KA19AB1002', 1800.000, 14.000, 'MCC Central Depot'),
        ('MRF-TRUCK-03', 'KA19AB1003', 3000.000, 20.000, 'Kadri Transfer Depot'),
        ('MRF-TRUCK-04', 'KA19AB1004', 2600.000, 18.000, 'Kadri Transfer Depot')
)
INSERT INTO mangalore.trucks (truck_code, registration_number, capacity_kg, capacity_m3, home_depot_location_id)
SELECT t.truck_code, t.registration_number, t.capacity_kg, t.capacity_m3, l.id
FROM sample_trucks AS t
JOIN mangalore.locations AS l ON l.name = t.depot_name
ON CONFLICT (truck_code) DO UPDATE
SET
    registration_number = EXCLUDED.registration_number,
    capacity_kg = EXCLUDED.capacity_kg,
    capacity_m3 = EXCLUDED.capacity_m3,
    home_depot_location_id = EXCLUDED.home_depot_location_id,
    is_active = true,
    updated_at = now();

WITH sample_orders (
    order_code,
    customer_location_name,
    vendor_location_name,
    waste_type,
    estimated_weight_kg,
    service_window_start,
    service_window_end,
    notes
) AS (
    VALUES
        ('SO-SAMPLE-001', 'Kadri Park Apartments', 'EcoSort Baikampady Vendor', 'plastic', 180.000, NULL, NULL, 'Apartment dry waste bags'),
        ('SO-SAMPLE-002', 'Bejai Commercial Complex', 'EcoSort Baikampady Vendor', 'cardboard', 260.000, NULL, NULL, 'Flattened cartons from shops'),
        ('SO-SAMPLE-003', 'Hampankatta Retail Row', 'Coastal Plastics Bunder Vendor', 'plastic', 140.000, NULL, NULL, 'PET bottles and mixed packaging'),
        ('SO-SAMPLE-004', 'Falnir Office Block', 'Coastal Plastics Bunder Vendor', 'e-waste', 75.000, NULL, NULL, 'Small electronics from IT office'),
        ('SO-SAMPLE-005', 'Kankanady Market Cluster', 'GreenLoop Jeppu Vendor', 'organic', 520.000, NULL, NULL, 'Vegetable market organics'),
        ('SO-SAMPLE-006', 'Pumpwell Junction Mall', 'GreenLoop Jeppu Vendor', 'food', 410.000, NULL, NULL, 'Food court compostables'),
        ('SO-SAMPLE-007', 'Thokkottu Retail Street', 'GreenLoop Jeppu Vendor', 'organic', 330.000, NULL, NULL, 'Market sweep collection'),
        ('SO-SAMPLE-008', 'Urwa Stores Community', 'EcoSort Baikampady Vendor', 'paper', 95.000, NULL, NULL, 'Newspaper bundles'),
        ('SO-SAMPLE-009', 'Derebail Residential Ward', 'EcoSort Baikampady Vendor', 'plastic', 210.000, NULL, NULL, 'Ward dry waste pickup'),
        ('SO-SAMPLE-010', 'Kuloor Warehouse Row', 'Surathkal Metals Vendor', 'metal', 680.000, NULL, NULL, 'Steel scrap from warehouse'),
        ('SO-SAMPLE-011', 'Surathkal College Campus', 'Surathkal Metals Vendor', 'appliance', 240.000, NULL, NULL, 'Discarded appliances'),
        ('SO-SAMPLE-012', 'Bondel School Zone', 'EcoSort Baikampady Vendor', 'paper', 155.000, NULL, NULL, 'School paper recycling'),
        ('SO-SAMPLE-013', 'Attavar Medical Campus', 'Coastal Plastics Bunder Vendor', 'plastic', 125.000, NULL, NULL, 'Non-medical dry plastic only'),
        ('SO-SAMPLE-014', 'Ullal Community Market', 'GreenLoop Jeppu Vendor', 'garden', 360.000, NULL, NULL, 'Leaves and market compostables'),
        ('SO-SAMPLE-015', 'Ladyhill Housing Block', 'EcoSort Baikampady Vendor', 'paper', 170.000, NULL, NULL, 'Mixed paper bags'),
        ('SO-SAMPLE-016', 'Mannagudda Temple Street', 'GreenLoop Jeppu Vendor', 'organic', 290.000, NULL, NULL, 'Temple flower and leaf waste'),
        ('SO-SAMPLE-017', 'Car Street Market Lane', 'Coastal Plastics Bunder Vendor', 'plastic', 190.000, NULL, NULL, 'Retail plastic collection'),
        ('SO-SAMPLE-018', 'Bolar Fisheries Row', 'GreenLoop Jeppu Vendor', 'organic', 470.000, NULL, NULL, 'Fish market compostables'),
        ('SO-SAMPLE-019', 'Pandeshwar Office Towers', 'Coastal Plastics Bunder Vendor', 'e-waste', 90.000, NULL, NULL, 'Office electronics pickup'),
        ('SO-SAMPLE-020', 'Nanthoor Junction Shops', 'EcoSort Baikampady Vendor', 'cardboard', 210.000, NULL, NULL, 'Shop cartons and dry waste'),
        ('SO-SAMPLE-021', 'Shaktinagar Community Hall', 'GreenLoop Jeppu Vendor', 'garden', 310.000, NULL, NULL, 'Garden waste bags'),
        ('SO-SAMPLE-022', 'Maryhill Ward Office', 'EcoSort Baikampady Vendor', 'plastic', 185.000, NULL, NULL, 'Ward dry waste'),
        ('SO-SAMPLE-023', 'Kavoor Commercial Strip', 'EcoSort Baikampady Vendor', 'paper', 145.000, NULL, NULL, 'Commercial paper sacks'),
        ('SO-SAMPLE-024', 'Kottara Chowki Stores', 'Coastal Plastics Bunder Vendor', 'plastic', 230.000, NULL, NULL, 'Storefront plastics'),
        ('SO-SAMPLE-025', 'Baikampady Factory Gate', 'Surathkal Metals Vendor', 'metal', 760.000, NULL, NULL, 'Factory scrap pickup'),
        ('SO-SAMPLE-026', 'Panambur Port Canteen', 'GreenLoop Jeppu Vendor', 'food', 385.000, NULL, NULL, 'Canteen food waste')
)
INSERT INTO mangalore.service_orders (
    order_code,
    customer_id,
    vendor_id,
    pickup_location_id,
    dropoff_location_id,
    waste_type,
    estimated_weight_kg,
    status,
    service_window_start,
    service_window_end,
    notes
)
SELECT
    o.order_code,
    c.id,
    v.id,
    pickup_location.id,
    vendor_location.id,
    o.waste_type,
    o.estimated_weight_kg,
    'PENDING',
    o.service_window_start::timestamptz,
    o.service_window_end::timestamptz,
    o.notes
FROM sample_orders AS o
JOIN mangalore.locations AS pickup_location ON pickup_location.name = o.customer_location_name
JOIN mangalore.customers AS c ON c.location_id = pickup_location.id
JOIN mangalore.locations AS vendor_location ON vendor_location.name = o.vendor_location_name
JOIN mangalore.vendors AS v ON v.location_id = vendor_location.id
ON CONFLICT (order_code) DO UPDATE
SET
    customer_id = EXCLUDED.customer_id,
    vendor_id = EXCLUDED.vendor_id,
    pickup_location_id = EXCLUDED.pickup_location_id,
    dropoff_location_id = EXCLUDED.dropoff_location_id,
    waste_type = EXCLUDED.waste_type,
    estimated_weight_kg = EXCLUDED.estimated_weight_kg,
    status = CASE
        WHEN mangalore.service_orders.status = 'COMPLETED' THEN mangalore.service_orders.status
        ELSE EXCLUDED.status
    END,
    service_window_start = EXCLUDED.service_window_start,
    service_window_end = EXCLUDED.service_window_end,
    notes = EXCLUDED.notes,
    updated_at = now();

COMMIT;
